. /usr/share/bash-completion/bash_completion
source <(kubectl completion bash)
source <(helm completion bash)
source <(kustomize completion bash)
eval "$(starship init bash)"

if [[ -e /host/run/docker.sock ]]; then
  export DOCKER_HOST=unix:///host/run/docker.sock
fi

if [[ -e /host/run/containerd/containerd.sock ]]; then
  export CONTAINERD_ADDRESS=unix:///host/run/containerd/containerd.sock
fi

if [[ -f /host/etc/kubernetes/admin.conf ]]; then
  export KUBECONFIG=/host/etc/kubernetes/admin.conf
fi
