. /usr/share/bash-completion/bash_completion
source <(kubectl completion bash)
source <(helm completion bash)
source <(kustomize completion bash)
eval "$(starship init bash)"

if [[ -e /host/run/docker.sock ]]; then
  export DOCKER_HOST=unix:///host/run/docker.sock
fi

if [[ -e /host/run/containerd/containerd.sock ]]; then
  export CONTAINERD_ADDRESS=unix:///host/run/containerd/containerd.sock
fi

if [[ -f /host/etc/kubernetes/admin.conf ]]; then
  export KUBECONFIG=/host/etc/kubernetes/admin.conf
fi

if [[ -f /host/etc/kubernetes/pki/etcd/ca.crt ]]; then
  export ETCDCTL_API=3
  export ETCDCTL_DIAL_TIMEOUT=3s
  export ETCDCTL_CACERT=/host/etc/kubernetes/pki/etcd/ca.crt
  export ETCDCTL_CERT=/host/etc/kubernetes/pki/etcd/healthcheck-client.crt
  export ETCDCTL_KEY=/host/etc/kubernetes/pki/etcd/healthcheck-client.key
fi
