name: Release

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  schedule:
  - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      run: echo "$GITHUB_TOKEN" | docker login ghcr.io --username "$GITHUB_ACTOR" --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: make build-all
      env:
        PULL_CACHE: "1"
        PUSH_CACHE: "1"
    - run: make all-push
